site_name: Focal Documentation
site_url: https://lkedward.github.io/focal-docs
repo_url: 'https://github.com/LKedward/focal'
edit_uri: ''
theme:
  name: 'material'
  # feature:
  #   tabs: true
  icon: 
    logo: material/memory

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
    # linenums: true
nav:
- Home: 'index.md'
- Getting started:
    - build.md
    - linking.md
    - quickstart.md
- User guide:
    - setup.md
    - memory.md
    - kernels.md
    - events.md
    - profiling.md
    - errors.md
    - advanced.md
- About:
    - contributing.md
    - about.md
- API Reference >: 'https://lkedward.github.io/focal'
